<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- rplidar a1m8 -->

  <joint name="laser_joint" type="fixed">
    <parent link="chassis" />
    <child link="laser_frame" />
    <!-- top center of chassis -->
    <origin xyz="${chassis_length/2} 0 ${chassis_height+0.0275}" rpy="0 0 0" />
  </joint>

  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <cylinder radius="0.035" length="0.0275" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <cylinder radius="0.035" length="0.0275" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.1" radius="0.035" length="0.0275">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>

  <!-- gazebo ray sensor with ros plugin -->
  <gazebo reference="laser_frame">
    <sensor name="laser" type="gpu_ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <output_rate>5.5</output_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>12</max>
          <resolution>0.1</resolution>
        </range>
        <!-- <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise> -->
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <!-- 2d output -->
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_frame</frame_name>
      </plugin>
    </sensor>
  </gazebo>


</robot>
