<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- IMU JOINT/LINK -->
  <!-- front top of chassis-->
  <joint name="imu_joint" type="fixed">
    <origin xyz="${chassis_length/2-0.01/2} 0.0 ${chassis_height/2 + 0.01/2}" />
    <parent link="chassis" />
    <child link="imu" />
    <!-- <dynamics damping="0.0" friction="0.0" /> -->
  </joint>

  <link name="imu">
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.001" x="0.01" y="0.01"
      z="0.01">
      <!-- same from collision -->
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_box>
  </link>
  <gazebo reference="imu">
    <material>Gazebo/Black</material>
  </gazebo>


  <!-- Gazebo imu sensor -->
  <!-- TODO: add noise -->
  <gazebo reference="imu">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <visualize>false</visualize>
    </sensor>
  </gazebo>

</robot>
