controller_manager:
  ros__parameters:
    # this is sent to each controller automatically
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# differential drive wheel controller
diff_cont:
  ros__parameters:
    # must be a double
    publish_rate: 30.0

    base_frame_id: base_link

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.34
    wheel_radius: 0.04

    # based on if input has a timestamp or not
    use_stamped_vel: false

# wheel joint broadcaster controller
# joint_broad:
#   ros__parameters:
