controller_manager:
  ros__parameters:
    # this is sent to each controller automatically
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# differential drive wheel controller
diff_cont:
  ros__parameters:
    use_sim_time: true
    # must be a double
    publish_rate: 30.0
    # based on if input has a timestamp or not
    use_stamped_vel: false
    # position_feedback: x
    # open_loop: x

    # TRANSFORM INFO
    base_frame_id: base_link
    enable_odom_tf: true
    odom_frame_id: odom

    # WHEEL INFO
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    # wheels_per_side: x
    wheel_separation: 0.34
    # wheel_separation_multiplier: x
    wheel_radius: 0.04
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # LINEAR LIMITS
    # linear:
    #   x:
    #     has_velocity_limits: false
    #     has_acceleration_limits: false
    #     has_jerk_limits: false
    #     min_velocity: NAN
    #     max_velocity: NAN
    #     min_acceleration: NAN
    #     max_acceleration: NAN
    #     min_jerk: NAN
    #     max_jerk: NAN

    # ANGULAR LIMITS
    # angular:
    #   z:
    #   has_velocity_limits: false
    #   has_acceleration_limits: false
    #   has_jerk_limits: false
    #   min_velocity: NAN
    #   max_velocity: NAN
    #   min_acceleration: NAN
    #   max_acceleration: NAN
    #   min_jerk: NAN
    #   max_jerk: NAN

# wheel joint broadcaster controller
joint_broad:
  ros__parameters:
    use_sim_time: true
