# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

twist_mux:
  ros__parameters:
    topics:
      navigation:
      # TODO: change this back to nav_vel
        topic: cmd_vel
        timeout: 0.5
        priority: 10
      keyboard:
        topic: key_vel
        timeout: 0.5
        priority: 90
      joystick:
        topic: joy_vel
        timeout: 0.5
        priority: 100
      # tablet:
      #   topic: tab_vel
      #   timeout: 0.5
      #   priority: 10

    # locks:
    #   pause:
    #     topic: pause_navigation
    #     timeout: 0.0
    #     # Same priority as joystick control, so it'll not block it.
    #     priority: 100
    #   loop_closure:
    #     topic: stop_closing_loop
    #     timeout: 0.0
    #     priority: 200
    #   joystick:
    #     topic: joy_priority
    #     timeout: 0.0
    #     priority: 100
